{
 "title": "Application",
 "description": "A dashboard to visualize Cats Effect runtime metrics. ",
 "tags": [ "cats-effect" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "prometheus", "label": "Data Source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(cats_effect_runtime_cpu_starvation_clock_drift_max_milliseconds,job)"
    }
   },
   {
    "name": "wstp_pool",
    "label": "WSTP pool",
    "query": {
     "query": "label_values(cats_effect_runtime_wstp_compute_thread_count,pool_id)"
    }
   },
   {
    "name": "wstp_worker_index",
    "label": "WSTP worker",
    "query": {
     "query": "label_values(cats_effect_runtime_wstp_worker_thread_event_count_total,worker_index)"
    }
   },
   { "name": "range", "label": "Range", "query": "1m, 2m, 5m, 10m, 30m" },
   { "name": "traceId", "label": "Trace ID" }
  ]
 },
 "panels": [
  { "title": "Tracing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Traces",
   "type": "xychart",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "filters": [
      { "id": "f1a5cec4", "operator": "=", "scope": "span" }
     ],
     "limit": 500,
     "metricsQueryType": "range",
     "spss": 5,
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Traces Table",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "filters": [
      { "id": "9d3c8809", "operator": "=", "scope": "span" }
     ],
     "limit": 500,
     "metricsQueryType": "range",
     "spss": 5,
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Trace",
   "type": "traces",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "filters": [
      { "id": "02551e08", "operator": "=", "scope": "span" },
      {
       "id": "span-name",
       "isCustomValue": false,
       "operator": "=",
       "scope": "span",
       "tag": "name",
       "value": [],
       "valueType": "string"
      },
      {
       "id": "status",
       "isCustomValue": false,
       "operator": "=",
       "scope": "intrinsic",
       "tag": "status",
       "valueType": "keyword"
      }
     ],
     "limit": 20,
     "metricsQueryType": "range",
     "query": "${traceId}",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "JVM Metrics - Garbage Collection",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 }
  },
  {
   "title": "Collections",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(jvm_gc_duration_seconds_count[1m])",
     "legendFormat": "{{jvm_gc_action}} - {{jvm_gc_name}}"
    }
   ]
  },
  {
   "title": "Pause Durations",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 7, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(jvm_gc_duration_seconds_sum{}[1m])/rate(jvm_gc_duration_seconds_count{}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Used After Last GC",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_after_last_gc_bytes",
     "legendFormat": "{{jvm_memory_pool_name}} - {{jvm_memory_type}}"
    }
   ]
  },
  { "title": "JVM Metrics - Classloading", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Classes loaded",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "jvm_class_loaded_total", "legendFormat": "loaded" }
   ]
  },
  {
   "title": "Class delta",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "delta(jvm_class_count[1m])", "legendFormat": "delta-1m" }
   ]
  },
  {
   "title": "Classes unloaded",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "jvm_class_unloaded_total", "legendFormat": "unloaded" }
   ]
  },
  {
   "title": "Currently Loaded Classes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "jvm_class_count", "legendFormat": "delta-1m" }
   ]
  },
  { "title": "JVM Metrics - CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "CPU Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 54 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jvm_cpu_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 4, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "jvm_cpu_recent_utilization_ratio",
     "legendFormat": "process"
    },
    {
     "expr": "avg_over_time(jvm_cpu_recent_utilization_ratio[15m])",
     "legendFormat": "process-15m"
    }
   ]
  },
  {
   "title": "GC Pressure",
   "type": "timeseries",
   "description": "The percent of time spent on Garbage Collection over all CPUs assigned to the JVM process.",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(job) (rate(jvm_gc_duration_seconds_count{job=\"$job\"}[1m])) / on(job) jvm_cpu_count",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "JVM Metrics - Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": "JVM Memory Pool Non Heap",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{jvm_memory_type=\"non_heap\"}",
     "legendFormat": "{{jvm_memory_pool_name}} - used"
    },
    {
     "expr": "jvm_memory_committed_bytes{jvm_memory_type=\"non_heap\"}",
     "legendFormat": "{{jvm_memory_pool_name}} - commited"
    },
    {
     "expr": "jvm_memory_limit_bytes{jvm_memory_type=\"non_heap\"}",
     "legendFormat": "{{jvm_memory_pool_name}} - limit"
    }
   ]
  },
  {
   "title": "JVM Memory Pool Heap",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{jvm_memory_type=\"heap\"}",
     "legendFormat": "{{jvm_memory_pool_name}} - used"
    },
    {
     "expr": "jvm_memory_committed_bytes{jvm_memory_type=\"heap\"}",
     "legendFormat": "{{jvm_memory_pool_name}} - commited"
    },
    {
     "expr": "jvm_memory_limit_bytes{jvm_memory_type=\"heap\"}",
     "legendFormat": "{{jvm_memory_pool_name}} - limit"
    }
   ]
  },
  { "title": "JVM Metrics - Thread", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 } },
  {
   "title": "Thread Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 76 },
   "targets": [
    { "expr": "jvm_thread_count", "legendFormat": "{{jvm_thread_state}}" }
   ]
  },
  { "title": "CPU starvation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 } },
  {
   "title": "Overview",
   "type": "text",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 86 },
   "options": {
    "content": "The [starvation checker](https://typelevel.org/cats-effect/docs/core/starvation-and-tuning) is a runtime assertion that any latency higher than the threshold (by default, 100 milliseconds) is bad and deserves a warning. The common causes:\n- Blocking tasks\n- Compute-bound work\n- Not enough CPUs\n- Too many threads\n- Burst credit contention\n- Process contention\n\n"
   }
  },
  {
   "title": "Clock drift [current]",
   "type": "gauge",
   "description": "The current clock drift",
   "gridPos": { "h": 8, "w": 4, "x": 7, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cats_effect_runtime_cpu_starvation_clock_drift_current_milliseconds{job=\"${job:value}\"}",
     "legendFormat": "current"
    }
   ]
  },
  {
   "title": "Starvations [$range]",
   "type": "timeseries",
   "description": "The current number of time CPU starvation has occurred",
   "gridPos": { "h": 8, "w": 6, "x": 11, "y": 86 },
   "targets": [
    {
     "expr": "increase(cats_effect_runtime_cpu_starvation_count_total{job=\"${job:value}\"}[$range])",
     "legendFormat": "Starvations"
    }
   ]
  },
  {
   "title": "Clock drift",
   "type": "timeseries",
   "description": "The current (last) and max (since the launch) observed clock drift in milliseconds",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "cats_effect_runtime_cpu_starvation_clock_drift_current_milliseconds{job=\"${job:value}\"}",
     "legendFormat": "Current"
    },
    {
     "expr": "cats_effect_runtime_cpu_starvation_clock_drift_max_milliseconds{job=\"${job:value}\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Work-Stealing Thread Pool | Compute",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 94 }
  },
  {
   "title": "Overview",
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 95 },
   "options": {
    "content": "This dashboard evaluates the utilization of compute threads in the [Cats Effect](https://github.com/typelevel/cats-effect) runtime:\n- Thread pool utilization - monitor the utilization of the worker threads\n- Blocking and searching threads - identify bottlenecks by tracking blocked and searching threads\n- Fiber management - understand fiber enqueue trends\n"
   }
  },
  {
   "title": "Worker threads",
   "type": "stat",
   "description": "The number of worker thread instances backing the work-stealing thread pool (WSTP)",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cats_effect_runtime_wstp_compute_thread_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active threads",
   "type": "stat",
   "description": "The number of active worker thread instances currently executing fibers on the compute thread pool",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 95 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cats_effect_runtime_wstp_compute_thread_active_count{job=\"${job:value}\", pool_id=\"${wstp_pool:value}\"}",
     "legendFormat": "active"
    }
   ]
  },
  {
   "title": "Blocking threads",
   "type": "stat",
   "description": "The number of worker thread instances that can run blocking actions on the compute thread pool",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 95 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cats_effect_runtime_wstp_compute_thread_blocked_count{job=\"${job:value}\", pool_id=\"${wstp_pool:value}\"}",
     "legendFormat": "blocked"
    }
   ]
  },
  {
   "title": "Active",
   "type": "timeseries",
   "description": "The number of active worker thread instances currently executing fibers on the compute thread pool",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 103 },
   "targets": [
    {
     "expr": "sum(cats_effect_runtime_wstp_compute_thread_active_count{job=\"${job:value}\", pool_id=\"${wstp_pool:value}\"})",
     "legendFormat": "Active"
    }
   ]
  },
  {
   "title": "Blocking",
   "type": "timeseries",
   "description": "The number of worker thread instances that can run blocking actions on the compute thread pool",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 103 },
   "targets": [
    {
     "expr": "sum(cats_effect_runtime_wstp_compute_thread_blocked_count{job=\"${job:value}\", pool_id=\"${wstp_pool:value}\"})",
     "legendFormat": "Blocking"
    }
   ]
  },
  {
   "title": "Searching",
   "type": "timeseries",
   "description": "The number of worker thread instances currently searching for fibers to steal from other worker threads",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 111 },
   "targets": [
    {
     "expr": "sum(cats_effect_runtime_wstp_compute_thread_searching_count{job=\"${job:value}\", pool_id=\"${wstp_pool:value}\"})",
     "legendFormat": "Searching"
    }
   ]
  },
  {
   "title": "Enqueued fibers [$range]",
   "type": "timeseries",
   "description": "The total number of fibers enqueued on all local queues",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 111 },
   "targets": [
    {
     "expr": "sum(increase(cats_effect_runtime_wstp_compute_fiber_enqueued_count{job=\"${job:value}\", pool_id=\"${wstp_pool:value}\"}[$range]))",
     "legendFormat": "Enqueued"
    }
   ]
  },
  {
   "title": "Suspended fibers [$range]",
   "type": "timeseries",
   "description": "The number of fibers which are currently asynchronously suspended",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 119 },
   "targets": [
    {
     "expr": "sum(increase(cats_effect_runtime_wstp_compute_fiber_suspended_count{job=\"${job:value}\", pool_id=\"${wstp_pool:value}\"}[$range]))",
     "legendFormat": "Suspended"
    }
   ]
  },
  {
   "title": "Work-Stealing Thread Pool | Worker Thread",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 127 }
  },
  {
   "title": "Events per state [$range]",
   "type": "timeseries",
   "description": "The total number of events that happend to the worker thread",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 128 },
   "targets": [
    {
     "expr": "sum (increase(cats_effect_runtime_wstp_worker_thread_event_count_total{job=\"${job:value}\", pool_id=\"${wstp_pool:value}\", worker_index=~\"${wstp_worker_index:regex}\"}[$range])) by (worker_index, thread_event)",
     "legendFormat": "Worker {{ worker_index }} - {{ thread_event }}"
    }
   ]
  },
  {
   "title": "Idle (parked) duration [$range]",
   "type": "timeseries",
   "description": "The total amount of time in nanoseconds that this worker thread has been parked",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 128 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "sum (increase(cats_effect_runtime_wstp_worker_thread_idle_duration_nanoseconds_total{job=\"${job:value}\", pool_id=\"${wstp_pool:value}\", worker_index=~\"${wstp_worker_index:regex}\"}[$range])) by (worker_index)",
     "legendFormat": "Worker {{ worker_index }}"
    }
   ]
  },
  {
   "title": "Work-Stealing Thread Pool | Local Queue",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 139 }
  },
  {
   "title": "Enqueued fibers",
   "type": "timeseries",
   "description": "The number of currently enqueued fibers",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 140 },
   "targets": [
    {
     "expr": "sum(cats_effect_runtime_wstp_worker_localqueue_fiber_enqueued_count{job=\"${job:value}\", pool_id=\"${wstp_pool:value}\", worker_index=~\"${wstp_worker_index:regex}\"}) by (worker_index)",
     "legendFormat": "Queue {{ worker_index }}"
    }
   ]
  },
  {
   "title": "Total fibers [$range]",
   "type": "timeseries",
   "description": "The total number of fibers enqueued during the lifetime of the local queue",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 140 },
   "targets": [
    {
     "expr": "sum(increase(cats_effect_runtime_wstp_worker_localqueue_fiber_count_total{job=\"${job:value}\", pool_id=\"${wstp_pool:value}\", worker_index=~\"${wstp_worker_index:regex}\"}[$range])) by (worker_index)",
     "legendFormat": "Queue {{ worker_index }}"
    }
   ]
  },
  {
   "title": "Stolen fibers [$range]",
   "type": "timeseries",
   "description": "The total number of stolen fibers by other worker threads",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 150 },
   "targets": [
    {
     "expr": "sum(increase(cats_effect_runtime_wstp_worker_localqueue_fiber_count_total{job=\"${job:value}\", pool_id=\"${wstp_pool:value}\", worker_index=~\"${wstp_worker_index:regex}\"}[$range])) by (worker_index)",
     "legendFormat": "Queue {{ worker_index }}"
    }
   ]
  },
  {
   "title": "Successful steal attempts [$range]",
   "type": "timeseries",
   "description": "The total number of successful steal attempts by other worker threads",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 150 },
   "targets": [
    {
     "expr": "sum(increase(cats_effect_runtime_wstp_worker_localqueue_fiber_steal_attempt_count_total{job=\"${job:value}\", pool_id=\"${wstp_pool:value}\", worker_index=~\"${wstp_worker_index:regex}\"}[$range])) by (worker_index)",
     "legendFormat": "Queue {{ worker_index }}"
    }
   ]
  },
  {
   "title": "Spilled over fibers [$range]",
   "type": "timeseries",
   "description": "The total number of fibers spilled over to the external queue",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 159 },
   "targets": [
    {
     "expr": "sum(increase(cats_effect_runtime_wstp_worker_localqueue_fiber_spillover_count_total{job=\"${job:value}\", pool_id=\"${wstp_pool:value}\", worker_index=~\"${wstp_worker_index:regex}\"}[$range])) by (worker_index)",
     "legendFormat": "Queue {{ worker_index }}"
    }
   ]
  },
  {
   "title": "Work-Stealing Thread Pool | Timer Heap",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 169 }
  },
  {
   "title": "Next due",
   "type": "timeseries",
   "description": "The time in nanoseconds till the next due to fire",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 170 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "sum (cats_effect_runtime_wstp_worker_timerheap_next_due_nanoseconds{job=\"${job:value}\", pool_id=\"${wstp_pool:value}\", worker_index=~\"${wstp_worker_index:regex}\"}) by (worker_index)",
     "legendFormat": "Timer {{worker_index}}"
    }
   ]
  },
  {
   "title": "Outstanding timers",
   "type": "timeseries",
   "description": "The current number of the outstanding timers that remain to be executed",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 170 },
   "targets": [
    {
     "expr": "sum (cats_effect_runtime_wstp_worker_timerheap_outstanding_count{job=\"${job:value}\", pool_id=\"${wstp_pool:value}\", worker_index=~\"${wstp_worker_index:regex}\"}) by (worker_index)",
     "legendFormat": "Timer {{worker_index}}"
    }
   ]
  },
  {
   "title": "Timers [$range]",
   "type": "timeseries",
   "description": "The total number of timers per state",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 179 },
   "targets": [
    {
     "expr": "sum (increase(cats_effect_runtime_wstp_worker_timerheap_timer_count_total{job=\"${job:value}\", pool_id=\"${wstp_pool:value}\", worker_index=~\"${wstp_worker_index:regex}\"}[$range])) by (worker_index, timer_state)",
     "legendFormat": "Timer {{worker_index}} - {{ timer_state }}"
    }
   ]
  },
  {
   "title": "Packed [$range]",
   "type": "timeseries",
   "description": "The total number of times the heap packed itself to remove canceled timers",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 179 },
   "targets": [
    {
     "expr": "sum (increase(cats_effect_runtime_wstp_worker_timerheap_packed_count_total{job=\"${job:value}\", pool_id=\"${wstp_pool:value}\", worker_index=~\"${wstp_worker_index:regex}\"}[$range])) by (worker_index)",
     "legendFormat": "Timer {{worker_index}}"
    }
   ]
  },
  {
   "title": "Work-Stealing Thread Pool | Poller",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 188 }
  },
  {
   "title": "Outstanding operations",
   "type": "timeseries",
   "description": "The current number of outstanding operations per category",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 189 },
   "targets": [
    {
     "expr": "sum by (worker_index, poller_operation) (cats_effect_runtime_wstp_worker_poller_operation_outstanding_count{job=\"${job:value}\", pool_id=\"${wstp_pool:value}\", worker_index=~\"${wstp_worker_index:regex}\"})",
     "legendFormat": "Poller {{ worker_index }} - {{ poller_operation }}"
    }
   ]
  },
  {
   "title": "Total operations [$range]",
   "type": "timeseries",
   "description": "The total number of operations per category and outcome",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 189 },
   "targets": [
    {
     "expr": "sum by (worker_index, poller_operation, poller_opration_status) (increase(cats_effect_runtime_wstp_worker_poller_operation_count_total{job=\"${job:value}\", pool_id=\"${wstp_pool:value}\", worker_index=~\"${wstp_worker_index:regex}\"}[$range]))",
     "legendFormat": "Poller {{ worker_index }} - {{ poller_operation }}"
    }
   ]
  }
 ]
}